config/routes.rb
Rails.application.routes.draw do

  resources :parts

  get '/thanks/' => 'home#thanks', :as => :thanks
  get '/get_customer/' => 'home#get_customer'
  get '/get_serial_numbers/' => 'home#get_serial_numbers'
  match '/warrantyregistration_edit/' => 'home#warrantyregistration_edit', :as => :warrantyregistration_edit, via: :get  
  match '/warrantyregistration' => 'home#warrantyregistration', :as => :warrantyregistration, via: :get
  match '/warrantyregistration/:id' => 'home#warrantyregistration_update', :as => :warrantyregistration_update, via: :patch
  resources :colours

  resources :settings

  #resources :sale_to_customers 
  resources :customer_sales_history, :as => :sale_to_customers, :controller => :sale_to_customers

  get '/get_customer_details/' => 'sale_to_customers#get_customer'
  
  resources :customers
    
   match '/user' => 'settings#index',:as => :users, via: :get
   match '/users/new' => 'settings#new', :as => :new_user, via: :get
   match '/user/:id' => 'settings#show', :as => :show_user, via: :get
   match '/users/:id/edit' => 'settings#edit', :as => :edit_user, via: :get

  match '/serialnumbers' => 'equipment#index',:as => :serialnumbers, via: :get
  match '/equipments/get_models' => 'equipment#get_models', via: :get
  resources :equipment do
    post :import,on: :collection
  end

  resources :retailer_groups
  
  resources :retailer_sales_history, :as => :sale_histories,:controller => :sale_histories
  resources :sale_histories do
      collection do 
        get :equipment_list_by_srno
        get :equipment_detail
        get :retailer_list_by_srno
      end
  end

  get 'jobs/get_serial_numbers/' => 'home#get_serial_numbers'
  get 'jobs/check_serial_key/' => 'jobs#check_serial_key'
  get 'warranties/check_serial_key/' => 'reports#check_serial_key'

  match '/jobs/new/:key' => 'jobs#new', :as => :new_jobs_with_params, via: :get
  match '/warranties/new/:key' => 'reports#new', :as => :new_warranties_with_params, via: :get

  resources :warranties, :as => :warranties, :controller => :reports
  resources :service_history, :as => :jobs, :controller => :jobs
  #resources :jobs, :as :service_history

  resources :accessories

  resources :models

  resources :brands

  match '/user' => 'users#create', :as => :create_store, via: :post
  match '/stores' => 'users#index',:as => :stores, via: :get
  match '/stores/new' => 'users#new', :as => :new_store, via: :get
  match '/stores/:id' => 'users#show', :as => :show_store, via: :get
  match '/stores/:id/edit' => 'users#edit', :as => :edit_store, via: :get

  
  devise_scope :user do
    get ":contact_person/sign_in" => "devise/sessions#new"
  end  
  
  devise_for :users
  
  match '/users/serialnumbers' => 'users#serial_key_list', :as => :user_key, via: :get
  resources :users do
    collection do
      get :serial_key_list
      get :check_email_uniq
      get :check_contact_person_uniq
    end
  end


  resources :retailers do
    collection do
        post :registration
    end
  end
 
  root 'home#index'

end

app/models/sale_history.rb
class SaleHistory < ActiveRecord::Base
  belongs_to :equipment
  belongs_to :brand
  belongs_to :model
  belongs_to :seller , :class_name=> :User , :foreign_key => "seller_id"
  belongs_to :buyer , :class_name=> :User , :foreign_key => "buyer_id"

  validates :buyer_id, :presence => { :message => "Invalid Retailer Name, Please try with valid Retailer Name" }
  validates :equipment_id, :presence => { :message => "Invalid Serial Number, Please try valid Serial Number " }
  # accepts_nested_attributes_for :equipment

  scope :recent, -> { order('created_at desc')  }
end

app/controllers/sale_histories_controller.rb
class SaleHistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin , :except => [:equipment_list_by_srno, :equipment_detail, :retailer_list_by_srno]
  before_action :set_sale_history, only: [:show, :edit, :update, :destroy]

  # GET /sale_histories
  # GET /sale_histories.json
  def index
    @search = SaleHistory.recent.search(params[:q])
    @sale_histories = @search.result.includes(:equipment,:brand,:model,:buyer).paginate(:page => params[:page], :per_page => 12)
  end

  # GET /sale_histories/1
  # GET /sale_histories/1.json
  def show
  end

  # GET /sale_histories/new
  def new
    @sale_history = SaleHistory.new
  end

  # GET /sale_histories/1/edit
  def edit
  end

  # POST /sale_histories
  # POST /sale_histories.json
  def create
    @sale_history = SaleHistory.new(sale_history_params)
    @equipment = Equipment.find(params[:sale_history][:equipment_id])
    @sale_history.model_id = @equipment.model_id
    @sale_history.brand_id = @equipment.brand_id
    @sale_history.serial_no = @equipment.serial_number
    if @equipment.sold_to_retailer == true
      redirect_to new_sale_history_path, notice: "Serial number (#{@equipment.serial_number}) has already been registered" 
      return
    end
    respond_to do |format|
      if @sale_history.save
        @equipment.sold_to_retailer = true
        @equipment.retailer_id = params[:sale_history][:buyer_id]
        @equipment.save
        format.html { redirect_to sale_histories_path, notice: 'Data was successfully created.' }
        format.json { render :show, status: :created, location: @sale_history }
      else
        format.html { render :new }
        format.json { render json: @sale_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sale_histories/1
  # PATCH/PUT /sale_histories/1.json
  def update
    @equipment = Equipment.find(params[:sale_history][:equipment_id])
    if @sale_history.equipment_id != @equipment.id and @equipment.sold_to_retailer == true
      redirect_to edit_sale_history_path(@sale_history), notice: "Serial number (#{@equipment.serial_number}) has already been registered" 
      return
    elsif @equipment.sold_to_retailer != true
      @equipment.sold_to_retailer = true
      @equipment.retailer_id = params[:sale_history][:buyer_id]
      @equipment.save
      equipment_old = @sale_history.equipment
      equipment_old.sold_to_retailer = false
      equipment_old.save
    else
    end
    respond_to do |format|
      if @sale_history.update(sale_history_params)
        format.html { redirect_to sale_histories_path, notice: 'Data was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale_history }
      else
        format.html { render :edit }
        format.json { render json: @sale_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_histories/1
  # DELETE /sale_histories/1.json
  def destroy
    @sale_history.destroy
    respond_to do |format|
      format.html { redirect_to sale_histories_path, notice: 'Data was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def equipment_list_by_srno

      sr_no = params[:query]
      @equipment = Equipment.select("equipment.id,equipment.serial_number")
                  .where("equipment.serial_number LIKE ?","%#{sr_no}%")

      respond_to do |format|
        format.json { render json: @equipment   }
      end

  end

  def equipment_detail
      id = params[:id]
      @equipment = Equipment.select("users.contact_person as rname, models.name as mname,brands.name as bname,colours.name as cname")
                  .joins(:model,:brand,:colour,:retailer)
                  .where("equipment.id = ? ",id)
      if !@equipment.present?
        @equipment = Equipment.select("models.name as mname,brands.name as bname,colours.name as cname")
                  .joins(:model,:brand,:colour)
                  .where("equipment.id = ? ",id)
      end     
      respond_to do |format|
        format.json { render json: @equipment.try(:first)   }
      end
  end

  def retailer_list_by_srno
       sr_no = params[:query]
       @retailer = User.retailer.select("id,contact_person AS usr_name").where("users.contact_person LIKE ? ","%#{sr_no}%")
      respond_to do |format|
        format.json { render json: @retailer }
      end
   
  end 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale_history
      @sale_history = SaleHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_history_params
      params.require(:sale_history).permit(:equipment_id, :buyer_id, :selling_date).merge(seller_id: current_user.id)
      # .merge(seller_id: current_user.id,equipment_attributes: [:sold_to_retailer=>true ])
    end
end

app/helpers/sale_histories_helper.rb
module SaleHistoriesHelper
end

app/views/sale_histories/_autocomp.js.erb
<script type="text/javascript" >
  function display_equipment_detail(item) {
    $('.equipment_id_hidden').val(item.value);
    $.get('/sale_histories/equipment_detail', { id: item.value }, function (data) {
        $('span.brand_name').text(data.bname);
        $('span.model_name').text(data.mname);
        $('span.colour_name').text(data.cname);

    });
  }
  function set_hidden_id(item) {
    $('.customer_id_hidden').val(item.value);
  }

  $(document).ready(function(){
  	  $('.typeahead_equipment').typeahead({
          ajax: '/sale_histories/equipment_list_by_srno',
          displayField: 'serial_number',
          valueField: 'id',
          onSelect: display_equipment_detail
      });
      $('.typeahead_customer').typeahead({
          ajax: '/sale_histories/retailer_list_by_srno',
          displayField: 'usr_name',
          valueField: 'id',
          onSelect: set_hidden_id
      });
    $('.sales_search_div').hide();
      $('input#sales_filter_ckbox').click(function(){
          // If checked
          if ($("#sales_filter_ckbox").is(":checked"))
          {
              //show the hidden div
              $(".sales_search_div").show();
          }
          else
          {
              //otherwise, hide it
              $(".sales_search_div").hide();
          }
        });
      
  });
</script>

app/views/sale_histories/_form.html.haml
= form_for @sale_history do |f|
  - if @sale_history.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale_history.errors.count, "error")} prohibited this sale_history from being saved:"
      %ul
        - @sale_history.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :equipment_id, :class => 'control-label'
    .controls
      = text_field_tag "equipment_id",@sale_history.try(:equipment).try(:serial_number), :required => true, :class => 'form-control typeahead_equipment',:placeholder=>"Search serial numnber...",:autocomplete => "off"
      = f.hidden_field :equipment_id, :class => 'form-control equipment_id_hidden'
  .form-group
    = label_tag "Brand", raw("Brand : <span class=\"brand_name\">#{@sale_history.try(:equipment).try(:brand).try(:name)}</span>"), {:class => 'control-label'}
  .form-group
    = label_tag "Model", raw("Model : <span class=\"model_name\">#{@sale_history.try(:equipment).try(:model).try(:name)}</span>"),{:class => 'control-label'}
  .form-group
    = label_tag "Colour", raw("Colour : <span class=\"colour_name\">#{@sale_history.try(:equipment).try(:colour).try(:name)}</span>"),{:class => 'control-label'}
  .form-group
    = f.label :customer_id,'Store Name', :class => 'control-label'
    .controls
      = f.select :buyer_id,User.retailer.all.map{|b| [b.contact_person,b.id]},{ :selected => User.find_by_contact_person('GoMotorised').id}, :class => 'form-control'
      =# text_field_tag "customer_id",@sale_history.try(:buyer).try(:user_name), :required => true, :class => 'form-control typeahead_customer',:autocomplete => "off",:placeholder=>"Search Store..."
      =# f.hidden_field :buyer_id, :class => 'form-control customer_id_hidden'
  .form-group
    = f.label :selling_date,"Purchase Date", :class => 'control-label'
    .controls
      = f.date_select :selling_date, :class => 'form-control'

  = f.submit "Save", :class => 'btn btn-primary'
  = link_to "Cancel",  sale_histories_path, :class => 'btn btn-default'

  = render 'autocomp.js'

app/views/sale_histories/edit.html.haml
.page-header
  %h1.title Editing Sell To Retailer
= render 'form'

app/views/sale_histories/index.html.haml
= search_form_for @search, :url => sale_histories_path do |f|
  / Search by Serial number
  .form-group
    = f.label :serial_no_eq, "Serial Number Search"
    = f.text_field :serial_no_eq
  .form-group
    %strong Advanced Filters
    %input{:name => "vehicle", :type => "checkbox", :value => "Car", :id => 'sales_filter_ckbox'}/ 
  / Search by first name
  .sales_search_div
    / Search by Purchase between
    .form-group
      = f.label :selling_date_gteq, "Purchase Date Between"
      = f.date_select :selling_date_gteq, :order => [:day, :month, :year], :include_blank => true
      = f.label :selling_date_lteq, "and"
      = f.date_select :selling_date_lteq, :order => [:day, :month, :year], :include_blank => true
    / Search by Brand name
    .form-group
      = f.label :brand_name_cont, "Brand name"
      = f.text_field :brand_name_cont
    / Search by Model name
    .form-group
      = f.label :model_name_cont, "Model name"
      = f.text_field :model_name_cont
      / Search by retailer name
    .form-group
      = f.label :buyer_contact_person_cont, "Store Name"
      = f.text_field :buyer_contact_person_cont

  .actions= f.submit "Search"
  %br
.page-header
  %h1.title Sales History
-if !@sale_histories.present?
  %center
    %h2 No Record Found
-else
  %table.table.table-hover
    %thead
      %tr
        %th Serial no
        %th Brand
        %th Model
        %th Colour
        %th Store Name
        %th Purchase date
        %th Actions
    %tbody
    - @sale_histories.includes(:equipment,:buyer,:brand).each do |sale_history|
      %tr
        %td= link_to sale_history.try(:equipment).try(:serial_number),equipment_path(sale_history.try(:equipment).try(:id))
        %td= sale_history.try(:equipment).try(:brand).try(:name)
        %td= sale_history.try(:equipment).try(:model).try(:name)
        %td= sale_history.try(:equipment).try(:colour).try(:name)
        %td= link_to sale_history.try(:buyer).try(:contact_person),show_store_path(sale_history.try(:buyer_id))
        %td= sale_history.selling_date.try(:strftime,'%d %b %Y ')
        %td
          = link_to 'Edit', edit_sale_history_path(sale_history),:class => 'btn btn-warning btn-xs'
          = link_to 'Show', sale_history_path(sale_history), :class => 'btn btn-primary btn-xs'
          = link_to 'Destroy', sale_history, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger'
    
%br

= will_paginate @sale_histories, renderer: BootstrapPagination::Rails 

= link_to "Sell to Retailer", new_sale_history_path, :class => 'btn btn-primary'
= render 'autocomp.js'

app/views/sale_histories/new.html.haml
.page-header
  %h1.title Sell to Retailer

= render 'form'

app/views/sale_histories/show.html.haml
%p#notice= notice

%p
  %b Serial no:
  = link_to @sale_history.equipment.try(:serial_number),equipment_path(@sale_history.equipment_id)
%p
  %b Brand:
  = @sale_history.equipment.brand.try(:name)
%p
  %b Model:
  = @sale_history.equipment.model.try(:name)
%p
  %b Store Name:
  = @sale_history.buyer.try(:user_name)
%p
  %b Purchase date:
  = @sale_history.selling_date.try(:strftime,'%m-%d-%Y')

= link_to 'Edit', edit_sale_history_path(@sale_history)
\|
= link_to 'Back', sale_histories_path

app/views/sale_histories/user.html.haml
= form_for SaleHistory.new,:url=>user_sale_histories_path, :html => { :class => 'form-horizontal retailer_form_validate' }  do |f|
  .form-group
    = f.label :first_name, :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'form-control'
  .form-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'form-control'
  .form-group
    = f.label :price, :class => 'control-label'
    .controls
      = f.text_field :price, :class => 'form-control'
  .form-group
    = f.label :address , :class => 'control-label'
    .controls
      = f.text_field :address, :class => 'form-control'
  .form-group
    = f.label :town , :class => 'control-label'
    .controls
      = f.text_field :town, :class => 'form-control'
  .form-group
    = f.label :retailer_group, :class => 'control-label'
    .controls
      = f.select :id,RetailerGroup.all.map{|b| [b.name,b.id]},{ include_blank: true }, :class => 'form-control'
  .form-group
    = f.label :city, :class => 'control-label'
    .controls
      = f.text_field :city, :class => 'form-control'
  .form-group
    = f.label :mobile , :class => 'control-label'
    .controls
      = f.text_field :mobile, :class => 'form-control'
  .form-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'form-control', :rel=> @user.try(:id)
  = f.submit "Save", :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), retailers_path, :class => 'btn btn-default'