config/routes.rb
Rails.application.routes.draw do

  resources :parts

  get '/thanks/' => 'home#thanks', :as => :thanks
  get '/get_customer/' => 'home#get_customer'
  get '/get_serial_numbers/' => 'home#get_serial_numbers'
  match '/warrantyregistration_edit/' => 'home#warrantyregistration_edit', :as => :warrantyregistration_edit, via: :get  
  match '/warrantyregistration' => 'home#warrantyregistration', :as => :warrantyregistration, via: :get
  match '/warrantyregistration/:id' => 'home#warrantyregistration_update', :as => :warrantyregistration_update, via: :patch
  resources :colours

  resources :settings

  #resources :sale_to_customers 
  resources :customer_sales_history, :as => :sale_to_customers, :controller => :sale_to_customers

  get '/get_customer_details/' => 'sale_to_customers#get_customer'
  
  resources :customers
    
   match '/user' => 'settings#index',:as => :users, via: :get
   match '/users/new' => 'settings#new', :as => :new_user, via: :get
   match '/user/:id' => 'settings#show', :as => :show_user, via: :get
   match '/users/:id/edit' => 'settings#edit', :as => :edit_user, via: :get

  match '/serialnumbers' => 'equipment#index',:as => :serialnumbers, via: :get
  match '/equipments/get_models' => 'equipment#get_models', via: :get
  resources :equipment do
    post :import,on: :collection
  end

  resources :retailer_groups
  
  resources :retailer_sales_history, :as => :sale_histories,:controller => :sale_histories
  resources :sale_histories do
      collection do 
        get :equipment_list_by_srno
        get :equipment_detail
        get :retailer_list_by_srno
      end
  end

  get 'jobs/get_serial_numbers/' => 'home#get_serial_numbers'
  get 'jobs/check_serial_key/' => 'jobs#check_serial_key'
  get 'warranties/check_serial_key/' => 'reports#check_serial_key'

  match '/jobs/new/:key' => 'jobs#new', :as => :new_jobs_with_params, via: :get
  match '/warranties/new/:key' => 'reports#new', :as => :new_warranties_with_params, via: :get

  resources :warranties, :as => :warranties, :controller => :reports
  resources :service_history, :as => :jobs, :controller => :jobs
  #resources :jobs, :as :service_history

  resources :accessories

  resources :models

  resources :brands

  match '/user' => 'users#create', :as => :create_store, via: :post
  match '/stores' => 'users#index',:as => :stores, via: :get
  match '/stores/new' => 'users#new', :as => :new_store, via: :get
  match '/stores/:id' => 'users#show', :as => :show_store, via: :get
  match '/stores/:id/edit' => 'users#edit', :as => :edit_store, via: :get

  
  devise_scope :user do
    get ":contact_person/sign_in" => "devise/sessions#new"
  end  
  
  devise_for :users
  
  match '/users/serialnumbers' => 'users#serial_key_list', :as => :user_key, via: :get
  resources :users do
    collection do
      get :serial_key_list
      get :check_email_uniq
      get :check_contact_person_uniq
    end
  end


  resources :retailers do
    collection do
        post :registration
    end
  end
 
  root 'home#index'

end

app/models/retailer_group.rb
class RetailerGroup < ActiveRecord::Base
 has_many :retailers,->{where("role_id=2")},class_name: :User,:foreign_key=>:retailer_group_id
 scope :recent, -> { order('created_at desc')  }
end

app/controllers/retailer_groups_controller.rb
class RetailerGroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin
  before_action :set_retailer_group, only: [:show, :edit, :update, :destroy]

  # GET /retailer_groups
  # GET /retailer_groups.json
  def index
    @search = RetailerGroup.recent.search(params[:q])
    @retailer_groups= @search.result.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /retailer_groups/1
  # GET /retailer_groups/1.json
  def show
  end

  # GET /retailer_groups/new
  def new
    @retailer_group = RetailerGroup.new
  end

  # GET /retailer_groups/1/edit
  def edit
  end

  # POST /retailer_groups
  # POST /retailer_groups.json
  def create
    @retailer_group = RetailerGroup.new(retailer_group_params)

    respond_to do |format|
      if @retailer_group.save
        format.html { redirect_to retailer_groups_url, notice: 'Retailer group was successfully created.' }
        format.json { render :show, status: :created, location: @retailer_group }
      else
        format.html { render :new }
        format.json { render json: @retailer_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retailer_groups/1
  # PATCH/PUT /retailer_groups/1.json
  def update
    respond_to do |format|
      if @retailer_group.update(retailer_group_params)
        format.html { redirect_to retailer_groups_url, notice: 'Retailer group was successfully updated.' }
        format.json { render :show, status: :ok, location: @retailer_group }
      else
        format.html { render :edit }
        format.json { render json: @retailer_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retailer_groups/1
  # DELETE /retailer_groups/1.json
  def destroy
    @retailer_group.destroy
    respond_to do |format|
      format.html { redirect_to retailer_groups_url, notice: 'Retailer group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retailer_group
      @retailer_group = RetailerGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def retailer_group_params
      params.require(:retailer_group).permit(:name)
    end
end

app/helpers/retailer_groups_helper.rb
module RetailerGroupsHelper
end

app/views/retailer_groups/_form.html.haml
= form_for @retailer_group, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :required => true, :class => 'form-control'
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), retailer_groups_path, :class => 'btn btn-default'

app/views/retailer_groups/edit.html.haml
- model_class = RetailerGroup
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/retailer_groups/index.html.haml
= search_form_for @search, url: '/retailer_groups' do |f|
  / Retailer group Name Search 
  .form-control-col-sm-4
    = f.label :name_cont, "Buying Group Search"
    = f.text_field :name_cont
    = actions= f.submit "Search", class: 'btn btn-primary btn-xs'

- model_class = RetailerGroup
.page-header
  %h1 Buying Group
-if !@retailer_groups.present?
  %center
    %h2 No Record Found
-else
  %table.table.table-hover
    %thead
      %tr
        %th= model_class.human_attribute_name(:name)
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @retailer_groups.each do |retailer_group|
        %tr
          %td= retailer_group.name
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_retailer_group_path(retailer_group), :class => 'btn btn-warning btn-xs' unless RetailerGroup.find_by_name('GoMotorised').id == retailer_group.id 
            = link_to t('.show', :default => t("helpers.links.show")), retailer_group_path(retailer_group), :class => 'btn btn-primary btn-xs' unless RetailerGroup.find_by_name('GoMotorised').id == retailer_group.id 
            = link_to t('.destroy', :default => t("helpers.links.destroy")), retailer_group_path(retailer_group), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' unless RetailerGroup.find_by_name('GoMotorised').id == retailer_group.id 

= link_to t('.new', :default => t("helpers.links.new")), new_retailer_group_path, :class => 'btn btn-primary'

app/views/retailer_groups/new.html.haml
- model_class = RetailerGroup
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/retailer_groups/show.html.haml
- model_class = RetailerGroup
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @retailer_group.name


= link_to t('.back', :default => t("helpers.links.back")), retailer_groups_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_retailer_group_path(@retailer_group), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), retailer_group_path(@retailer_group), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'