config/routes.rb
Rails.application.routes.draw do

  resources :parts

  get '/thanks/' => 'home#thanks', :as => :thanks
  get '/get_customer/' => 'home#get_customer'
  get '/get_serial_numbers/' => 'home#get_serial_numbers'
  match '/warrantyregistration_edit/' => 'home#warrantyregistration_edit', :as => :warrantyregistration_edit, via: :get  
  match '/warrantyregistration' => 'home#warrantyregistration', :as => :warrantyregistration, via: :get
  match '/warrantyregistration/:id' => 'home#warrantyregistration_update', :as => :warrantyregistration_update, via: :patch
  resources :colours

  resources :settings

  #resources :sale_to_customers 
  resources :customer_sales_history, :as => :sale_to_customers, :controller => :sale_to_customers

  get '/get_customer_details/' => 'sale_to_customers#get_customer'
  
  resources :customers
    
   match '/user' => 'settings#index',:as => :users, via: :get
   match '/users/new' => 'settings#new', :as => :new_user, via: :get
   match '/user/:id' => 'settings#show', :as => :show_user, via: :get
   match '/users/:id/edit' => 'settings#edit', :as => :edit_user, via: :get

  match '/serialnumbers' => 'equipment#index',:as => :serialnumbers, via: :get
  match '/equipments/get_models' => 'equipment#get_models', via: :get
  resources :equipment do
    post :import,on: :collection
  end

  resources :retailer_groups
  
  resources :retailer_sales_history, :as => :sale_histories,:controller => :sale_histories
  resources :sale_histories do
      collection do 
        get :equipment_list_by_srno
        get :equipment_detail
        get :retailer_list_by_srno
      end
  end

  get 'jobs/get_serial_numbers/' => 'home#get_serial_numbers'
  get 'jobs/check_serial_key/' => 'jobs#check_serial_key'
  get 'warranties/check_serial_key/' => 'reports#check_serial_key'

  match '/jobs/new/:key' => 'jobs#new', :as => :new_jobs_with_params, via: :get
  match '/warranties/new/:key' => 'reports#new', :as => :new_warranties_with_params, via: :get

  resources :warranties, :as => :warranties, :controller => :reports
  resources :service_history, :as => :jobs, :controller => :jobs
  #resources :jobs, :as :service_history

  resources :accessories

  resources :models

  resources :brands

  match '/user' => 'users#create', :as => :create_store, via: :post
  match '/stores' => 'users#index',:as => :stores, via: :get
  match '/stores/new' => 'users#new', :as => :new_store, via: :get
  match '/stores/:id' => 'users#show', :as => :show_store, via: :get
  match '/stores/:id/edit' => 'users#edit', :as => :edit_store, via: :get

  
  devise_scope :user do
    get ":contact_person/sign_in" => "devise/sessions#new"
  end  
  
  devise_for :users
  
  match '/users/serialnumbers' => 'users#serial_key_list', :as => :user_key, via: :get
  resources :users do
    collection do
      get :serial_key_list
      get :check_email_uniq
      get :check_contact_person_uniq
    end
  end


  resources :retailers do
    collection do
        post :registration
    end
  end
 
  root 'home#index'

end

app/models/colour.rb
class Colour < ActiveRecord::Base
  belongs_to :user
  has_many :equipment
  validates :name, presence: true

end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin
  before_action :set_colour, only: [:show, :edit, :update, :destroy]

  # GET /colours
  # GET /colours.json
  def index
    @colours = Colour.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /colours/1
  # GET /colours/1.json
  def show
  end

  # GET /colours/new
  def new
    @colour = Colour.new
  end

  # GET /colours/1/edit
  def edit
  end

  # POST /colours
  # POST /colours.json
  def create
    @colour = Colour.new(colour_params)

    respond_to do |format|
      if @colour.save
        format.html { redirect_to colours_url, notice: 'Colour was successfully created.' }
        format.json { render :show, status: :created, location: @colour }
      else
        format.html { render :new }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colours/1
  # PATCH/PUT /colours/1.json
  def update
    respond_to do |format|
      if @colour.update(colour_params)
        format.html { redirect_to colours_url, notice: 'Colour was successfully updated.' }
        format.json { render :show, status: :ok, location: @colour }
      else
        format.html { render :edit }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colours/1
  # DELETE /colours/1.json
  def destroy
    @colour.destroy
    respond_to do |format|
      format.html { redirect_to colours_url, notice: 'Colour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colour
      @colour = Colour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colour_params
      params.require(:colour).permit(:name).merge(:user=>current_user)
    end
end

app/helpers/colours_helper.rb
module ColoursHelper
end

app/views/colours/_form.html.haml
= form_for @colour, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :required => true, :class => 'form-control'
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), colours_path, :class => 'btn btn-default'

app/views/colours/edit.html.haml
- model_class = Colour
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/colours/index.html.haml
- model_class = Colour
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
-if !@colours.present?
  %center
    %h2 No Record Found
-else
  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:name)
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @colours.each do |colour|
        %tr
          %td= colour.name
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_colour_path(colour), :class => 'btn btn-default btn-xs'
            = link_to t('.show', :default => t("helpers.links.show")), colour_path(colour), :class => 'btn btn-primary btn-xs'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), colour_path(colour), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_colour_path, :class => 'btn btn-primary'

app/views/colours/new.html.haml
- model_class = Colour
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/colours/show.html.haml
- model_class = Colour
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @colour.name
%p


= link_to t('.back', :default => t("helpers.links.back")), colours_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_colour_path(@colour), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), colour_path(@colour), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'