config/routes.rb
Rails.application.routes.draw do

  resources :parts

  get '/thanks/' => 'home#thanks', :as => :thanks
  get '/get_customer/' => 'home#get_customer'
  get '/get_serial_numbers/' => 'home#get_serial_numbers'
  match '/warrantyregistration_edit/' => 'home#warrantyregistration_edit', :as => :warrantyregistration_edit, via: :get  
  match '/warrantyregistration' => 'home#warrantyregistration', :as => :warrantyregistration, via: :get
  match '/warrantyregistration/:id' => 'home#warrantyregistration_update', :as => :warrantyregistration_update, via: :patch
  resources :colours

  resources :settings

  #resources :sale_to_customers 
  resources :customer_sales_history, :as => :sale_to_customers, :controller => :sale_to_customers

  get '/get_customer_details/' => 'sale_to_customers#get_customer'
  
  resources :customers
    
   match '/user' => 'settings#index',:as => :users, via: :get
   match '/users/new' => 'settings#new', :as => :new_user, via: :get
   match '/user/:id' => 'settings#show', :as => :show_user, via: :get
   match '/users/:id/edit' => 'settings#edit', :as => :edit_user, via: :get

  match '/serialnumbers' => 'equipment#index',:as => :serialnumbers, via: :get
  match '/equipments/get_models' => 'equipment#get_models', via: :get
  resources :equipment do
    post :import,on: :collection
  end

  resources :retailer_groups
  
  resources :retailer_sales_history, :as => :sale_histories,:controller => :sale_histories
  resources :sale_histories do
      collection do 
        get :equipment_list_by_srno
        get :equipment_detail
        get :retailer_list_by_srno
      end
  end

  get 'jobs/get_serial_numbers/' => 'home#get_serial_numbers'
  get 'jobs/check_serial_key/' => 'jobs#check_serial_key'
  get 'warranties/check_serial_key/' => 'reports#check_serial_key'

  match '/jobs/new/:key' => 'jobs#new', :as => :new_jobs_with_params, via: :get
  match '/warranties/new/:key' => 'reports#new', :as => :new_warranties_with_params, via: :get

  resources :warranties, :as => :warranties, :controller => :reports
  resources :service_history, :as => :jobs, :controller => :jobs
  #resources :jobs, :as :service_history

  resources :accessories

  resources :models

  resources :brands

  match '/user' => 'users#create', :as => :create_store, via: :post
  match '/stores' => 'users#index',:as => :stores, via: :get
  match '/stores/new' => 'users#new', :as => :new_store, via: :get
  match '/stores/:id' => 'users#show', :as => :show_store, via: :get
  match '/stores/:id/edit' => 'users#edit', :as => :edit_store, via: :get

  
  devise_scope :user do
    get ":contact_person/sign_in" => "devise/sessions#new"
  end  
  
  devise_for :users
  
  match '/users/serialnumbers' => 'users#serial_key_list', :as => :user_key, via: :get
  resources :users do
    collection do
      get :serial_key_list
      get :check_email_uniq
      get :check_contact_person_uniq
    end
  end


  resources :retailers do
    collection do
        post :registration
    end
  end
 
  root 'home#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, :except => [:new, :create, :show, :check_serial_key]
  before_action :is_admin
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    #@jobs = Job.all
     @search = Job.recent.search(params[:q])
     @jobs = @search.result.paginate(:page => params[:page], :per_page => 12)
      respond_to do |format|
        format.html
        format.csv { send_data @jobs.to_csv }
      end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @job.serial_number = params[:key]
    @equipment = Equipment.find_by_serial_number(params[:key])
     @search = Equipment.recent.search(params[:q])
  end

  def check_serial_key 
    @search = Equipment.recent.search(params[:q])
      if params[:q].present?
        @result = Equipment.find_by_serial_number(params[:q][:serial_number_eq])
      end
      if !@result.present?
        redirect_to new_warranty_path, notice: 'No Record Found.'
        return
      else
        redirect_to new_warranties_with_params_path(:key => @result.serial_number)
      end
  end

  # GET /jobs/1/edit
  def edit
      @equipment = Equipment.find_by_serial_number(@job.serial_number)
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to warranties_path, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to warranties_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:cost, :serial_number, :claim_amount, :date_of_job, :service_notes, :time_spent, :claimed, :warrenty_job, :servicetech)
    end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_autocomp.js.erb
<script type="text/javascript" >
  function display_equipment_detail(item) {
    $('#sno_job_key').val(item.value);
   
  }
  $(document).ready(function(){
    $('#claim_amount_id').hide();

    $('#job_claimed_yes').click(function () {
      $('#claim_amount_id').show('slow');
    });
    
    $('#job_claimed_no').click(function () {
          $('#claim_amount_id').hide('slow');
     });
    
    $('#sno_job_key').typeahead({
          ajax: '/get_serial_numbers',
          displayField: 'serial_number',
          valueField: 'id',
          onSelect: display_equipment_detail
      }); 
  });

</script>

app/views/reports/_form.html.haml
= form_for @job, :url=> @job.new_record? ? warranties_path : warranty_path(@job) do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg
  %br
  .form-group
    = f.label :serial_number, :class => 'control-label'
    .controls
      = f.text_field :serial_number, :readonly => true, :class => 'form-control'
  .form-group
    = label_tag "Brand", raw("Brand : <span class=\"brand_name\">#{@equipment.try(:brand).try(:name)}</span>"), {:class => 'control-label'}
  .form-group
    = label_tag "Model", raw("Model : <span class=\"model_name\">#{@equipment.try(:model).try(:name)}</span>"),{:class => 'control-label'}
  .form-group
    = label_tag "Colour", raw("Colour : <span class=\"colour_name\">#{@equipment.try(:colour).try(:name)}</span>"),{:class => 'control-label'}
  .form-group
    = label_tag "retailer", raw("Purchased From : <span class=\"retailer_name\">#{@equipment.try(:retailer).try(:contact_person)}</span>"),{:class => 'control-label'} 
  .form-group
    = f.label :date_of_job, :class => 'control-label'
    .controls
      = f.date_select :date_of_job,  :order => [:day, :month, :year], :class => 'form-control'
  .form-group
    = f.label :servicetech, :class => 'control-label'
    .controls
      = f.select :servicetech, User.recent.setting.map{|b| [b.first_name,b.first_name]}, :class => 'form-control' 
  .form-group
    = f.label :service_notes  , :class => 'control-label'
    .controls
      = f.text_area :service_notes, :class => 'form-control'
  .form-group
    = f.label :time_spent, :class => 'control-label'
    .controls
      =f.select(:time_spent, Job::TIME_SPENT)
  .form-group
    = f.label :cost, :class => 'control-label'
    .controls
      = f.text_field :cost, :class => 'form-control'
  .form-group
    = f.label :warrenty_job,"Warranty", :class => 'control-label' 
    = f.radio_button :warrenty_job, "Yes", :checked => true
    = f.label :warrenty_job, "Yes" 
    = f.radio_button :warrenty_job, "No"
    = f.label :warrenty_job, "No"
  #claimed_id.form-group
    = f.label :claimed, :class => 'control-label' 
    = f.radio_button :claimed, "Yes"
    = f.label :claimed, "Yes" 
    = f.radio_button :claimed, "No"
    = f.label :claimed, "No"
  #claim_amount_id.form-group
    = f.label :claim_amount, :class => 'control-label'
    .controls
      = f.text_field :claim_amount, :class => 'form-control'
  .actions
    = f.submit 'Save', :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), jobs_path, :class => 'btn btn-default'

app/views/reports/edit.html.haml
%h1 Editing job

= render 'form'
= render 'autocomp.js'

app/views/reports/index.html.haml
= search_form_for @search, :url=> warranties_path do |f|
  .form-group
    = f.label :equipment_brand_name_cont, "Brand name"
    = f.text_field :equipment_brand_name_cont
  .form-group
    = f.label :warrenty_job, :class => 'control-label' 
    = f.radio_button :warrenty_job_cont, "Yes" 
    = f.label :warrenty_job, "Yes" 
    = f.radio_button :warrenty_job_cont, "No" 
    = f.label :warrenty_job, "No" 
  .form-group
    = f.label :claimed, :class => 'control-label' 
    = f.radio_button :claimed_cont, "Yes" 
    = f.label :claimed, "Yes" 
    = f.radio_button :claimed_cont, "No" 
    = f.label :claimed, "No" 
  .actions= f.submit "Search"
  %br

.page-header
  %h1 Job History
-if !@jobs.present?
  %center
    %h2 No Record Found
-else
  %table.table.table-hover
    %thead
      %tr
        %th Date of job
        %th Serial Number
        %th Brand Name
        %th Service notes
        %th Time spent
        %th Cost
        %th Claimed
        %th Warranty
        %th Servicetech
        %th Claimed amount
        %th=t '.actions', :default => t("helpers.actions") 
    %tbody
      - @jobs.includes(:equipment).each do |job|
        %tr
          %td= job.try(:date_of_job).try(:strftime,"%d %b %Y ")
          %td= link_to job.try(:equipment).try(:serial_number), equipment_path(job.equipment.id)
          %td= job.try(:equipment).try(:brand).try(:name)
          %td= job.service_notes
          %td= job.time_spent
          %td= job.cost
          %td= job.claimed
          %td= job.warrenty_job
          %td= job.servicetech
          %td= job.claim_amount
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_warranty_path(job), :class => 'btn btn-warning btn-xs'
            = link_to t('.show', :default => t("helpers.links.show")), warranty_path(job), :class => 'btn btn-primary btn-xs'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), warranty_path(job), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
%br
= will_paginate @jobs, renderer: BootstrapPagination::Rails  
%p 
  %b Download link
= link_to "CSV", jobs_path(format: "csv") 

=# link_to 'New Job', new_job_path

app/views/reports/new.html.haml
%h1 New job

= search_form_for @search , url: '/warranties/check_serial_key/' do |f|
  / equipment no Search 
  .form-control-col-sm-4
    = f.label :serial_number_eq, "Serial Number Search"
    = f.text_field :serial_number_eq, :id => 'sno_job_key', :placeholder=>"Search serial number...", :autocomplete => "off"
    = actions = f.submit "Search", class: 'btn btn-primary btn-xs'

= render :partial => "form" if params[:key].present?
= render 'autocomp.js'

app/views/reports/show.html.haml
.page-header
  %h1 Equipment Details
%table.table.table-hover
  %thead
    %tr
      %th Serial Number
      %th Brand
      %th Model
      %th Colour
      %th warrenty(on months)
  %tbody
    %tr
      %td= @job.try(:equipment).try(:serial_number)
      %td= @job.try(:equipment).try(:brand).try(:name)
      %td= @job.try(:equipment).try(:model).try(:name)   
      %td= @job.try(:equipment).try(:colour).try(:name)       
      %td= @job.try(:equipment).try(:model).try(:warranty)
.page-header
  %h1 Retailer
%table.table.table-hover
  %thead
    %tr
      %th Store Name
      %th Purchase Date
  %tbody
    %tr
      %td= @job.try(:equipment).try(:retailer).try(:contact_person)
      %td= @job.try(:equipment).try(:sale_history).try(:selling_date).try(:strftime,"%d %b %Y ")
.page-header
  %h1 Customer
%table.table.table-hover
  %thead
    %tr
      %th First Name
      %th Last Name
      %th Purchase Date
  %tbody
    %tr
      %td= @job.try(:equipment).try(:customer).try(:first_name)
      %td= @job.try(:equipment).try(:customer).try(:last_name)
      %td= @job.try(:equipment).try(:purchase_date).try(:strftime,"%d %b %Y ")
.page-header
  %h1 Service Detail
%table.table.table-hover
  %thead
    %tr
      %th Date of job
      %th Notes
      %th Warrenty
      %th Claimed
      %th Time spent
      %th Servicetech
  %tbody
    %tr
      %td= @job.date_of_job.try(:strftime,"%d %b %Y ")
      %td= @job.service_notes
      %td= @job.warrenty_job
      %td= @job.claimed
      %td= @job.time_spent
      %td= @job.servicetech
= link_to t('.back', :default => t("helpers.links.back")), jobs_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_job_path(@job), :class => 'btn btn-default'